apiVersion: v2
appVersion: 0.38.1
description: Provides easy monitoring definitions for Kubernetes services, and deployment
  and management of Prometheus instances.
home: https://github.com/coreos/prometheus-operator
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- operator
- prometheus
maintainers:
- name: vsliouniaev
- name: bismarck
- email: gianrubio@gmail.com
  name: gianrubio
name: prometheus-operator
sources:
- https://github.com/coreos/kube-prometheus
- https://github.com/coreos/prometheus-operator
- https://coreos.com/operators/prometheus
version: 9.3.1
dependencies:
  - name: kube-state-metrics
    version: "2.8.10-20230116062306+6686075"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "1.10.*"
    repository: https://charts.helm.sh/stable
    condition: nodeExporter.enabled
  - name: grafana
    version: "5.3.0-20230118095212+fcb8363"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
    condition: grafana.enabled

